version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  app:
    image: my-app
    ports:
     - "8000:8080"
    depends_on:
      - db
  worker:
    image: my-worker
    depends_on:
      - db
