apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b
  namespace: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
        - name: mikroserwis-b
          image: mikroserwis-b:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: DB_NAME
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-b-service
  namespace: three-tier-app
spec:
  selector:
    app: mikroserwis-b
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
