apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-a
  namespace: three-tier-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mikroserwis-a
  template:
    metadata:
      labels:
        app: mikroserwis-a
    spec:
      containers:
        - name: mikroserwis-a
          image: mikroserwis-a:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.25"
            limits:
              memory: "500Mi"
              cpu: "0.5"
          env:
            - name: MIKROSERWIS_B_URL
              value: "http://mikroserwis-b-service:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-a-service
  namespace: three-tier-app
spec:
  selector:
    app: mikroserwis-a
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
